import { describe, expect, it } from 'vitest';
import nacl from 'tweetnacl';
import {
  BufferUtils,
  Hash,
  KeyPair,
  PublicKey,
  Signature,
} from '@nimiq/core';
import {
  canonicalizeNimiqAddress,
  deriveNimiqAddress,
} from '../src/auth/nimiq-address';
import {
  NIMIQ_MESSAGE_PREFIX,
  nimiqSignedMessageHash,
  verifyNimiqSignature,
} from '../src/auth/nimiq-verify';

// Non-circular proof for the production Nimiq verifier.
// Oracle: the official @nimiq/core package (Nimiq's Rust-to-WASM web client,
// v2.21.0). The Hub signMessage documentation
// (https://nimiq.github.io/api-reference/sign-message — verified 2026-09-11:
// "Prefixing and Hashing" defines the envelope as
// sign(sha256('\x16Nimiq Signed Message:\n' + message.length + message)) and
// its "Verification" section points at this library) defines the envelope.
// Oracle primitives verified in the installed package:
// - node_modules/@nimiq/core/nodejs/main-wasm/index.js: class Signature
//   (static create/deserialize/serialize), class PublicKey (constructor,
//   verify(signature, data), toAddress), class Hash (static computeSha256),
//   class KeyPair (static generate).
// - node_modules/@nimiq/core/lib/node/index.js: BufferUtils.fromUtf8.
// Nothing here is generated by the code under test: keys, addresses, hashes,
// and oracle signatures all come from @nimiq/core.

const HUB_PREFIX = 'Nimiq Signed Message:\n';

function challengeMessage(tag: string): string {
  return `TAKEOVER-AUTH:v1:${tag}:2026-09-11T12:00:00.000Z`;
}

describe('nimiq oracle (@nimiq/core)', () => {
  it('pins the official Hub message prefix byte-for-byte', () => {
    expect(NIMIQ_MESSAGE_PREFIX).toBe(HUB_PREFIX);
    expect(HUB_PREFIX).toHaveLength(23);
  });

  it('derives the same address as the official library', () => {
    const kp = KeyPair.generate();
    const official = kp.publicKey.toAddress().toUserFriendlyAddress();
    const mine = deriveNimiqAddress(new Uint8Array(kp.publicKey.serialize()));
    // Also proves the canonicalizer accepts official spaced user-friendly output
    // (the same shape listAccounts() returns to the frontend).
    expect(canonicalizeNimiqAddress(official)).toBe(mine);
  });

  it('accepts a signature produced by the official library', () => {
    const kp = KeyPair.generate();
    const message = challengeMessage('ef'.repeat(32));
    const officialAddress = kp.publicKey.toAddress().toUserFriendlyAddress();
    const data = BufferUtils.fromUtf8(HUB_PREFIX + message.length + message);
    const hash = Hash.computeSha256(data);
    const signature = Signature.create(kp.privateKey, kp.publicKey, hash);
    const ok = verifyNimiqSignature({
      address: canonicalizeNimiqAddress(officialAddress),
      message,
      signature: Buffer.from(signature.serialize()).toString('hex'),
      publicKey: Buffer.from(kp.publicKey.serialize()).toString('hex'),
    });
    expect(ok).toBe(true);
  });

  it('produces signatures the official library accepts (reverse cross-check)', () => {
    const kp = nacl.sign.keyPair();
    const message = challengeMessage('12'.repeat(32));
    const envelope = `${HUB_PREFIX}${message.length}${message}`;
    const officialHash = Hash.computeSha256(BufferUtils.fromUtf8(envelope));
    const mine = nacl.sign.detached(nimiqSignedMessageHash(message), kp.secretKey);
    // Same digest both sides: my envelope bytes hash to the official digest.
    expect(Buffer.from(officialHash)).toEqual(Buffer.from(nimiqSignedMessageHash(message)));
    const officialPublicKey = new PublicKey(kp.publicKey);
    expect(officialPublicKey.verify(Signature.deserialize(mine), officialHash)).toBe(true);
  });
});
